name = "prisma-test"
compatibility_date = "2023-08-23"

vars = { DB_URL = "http://127.0.0.1:54321", DB_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0" }

# Production environment configuration
[env.production]
workers_dev = true
