name = "prisma-test"
compatibility_date = "2023-08-23"

vars = { DB_URL = "http://127.0.0.1:54321", DB_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU" }

# Production environment configuration
[env.production]
workers_dev = true
